# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u043c\u0435\u0441\u0442\u0430')),
                ('is_archive', models.BooleanField(default=False, verbose_name='\u041c\u0435\u0441\u0442\u043e \u0432 \u0430\u0440\u0445\u0438\u0432\u0435')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255, verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b \u043c\u0435\u0441\u0442\u0430')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
            ],
            options={
                'ordering': ('name', 'id'),
                'verbose_name': '\u041c\u0435\u0441\u0442\u043e',
                'verbose_name_plural': '\u041c\u0435\u0441\u0442\u0430',
            },
        ),
    ]
