# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
