# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180331_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='events.Event'),
        ),
    ]
