# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180331_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='events',
        ),
    ]
