# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_blog_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
