# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20180403_1349'),
        ('events', '0004_tag_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created', 'id'), 'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043a \u0441\u043e\u0431\u044b\u0442\u0438\u044e', 'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u043a \u0441\u043e\u0431\u044b\u0442\u0438\u044f\u043c'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='event',
            new_name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='departurePoint',
            field=models.ManyToManyField(blank=True, related_name='departurePoints', to='places.Place', verbose_name='\u0422\u043e\u0447\u043a\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='event',
            name='destination',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='places.Place', verbose_name='\u0422\u043e\u0447\u043a\u0430 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f'),
        ),
    ]
